### ISSUE TITLE
Headless versie logging werkt niet juist?

### ISSUE THREAD

**Issue by iBeastM0de** [PlaceNL/Bot#11]
Het lijkt er op dat het loggen van de locatie van een nieuw geplaatst pixel niet overeenkomt met het daadwerkelijk geplaatste pixel. 

![image](https://user-images.githubusercontent.com/23477956/161395010-e5d4f6c5-d990-4085-851d-16c31028ce03.png)

**Comment by n9iels** [comment]
Ik observeer zojuist een pixel die geplaatst wordt buiten de aangeleverde map. `(153, 1)` geveriveerd en hij is ook echt geplaatst...

**Comment by RubenNL** [comment]
Is dit nogsteeds een probleem? Er zijn de afgelopen 24 uur veel aanpassingen gemaakt aan de bot.

**Comment by Inktvisje** [comment]
Lijkt me niet; dit komt wel overeen met de problemen die we hadden na de overgang naar een 2000x1000 canvas, welke allemaal zijn gefixt ondertussen.

**Comment by iBeastM0de** [comment]
> Is dit nogsteeds een probleem? Er zijn de afgelopen 24 uur veel aanpassingen gemaakt aan de bot.

Nee dit issue lijkt opgelost
